component: other-test-service

# This is only used by the build worklow,
# it determines how the component is built
# Docker only relevant when the argument
# 
build:
  project_file: src/Grid.Bot.csproj
  component_directory: ./.deploy

  additional_args:
    - -p:IMAGE_TAG=${{ env.NOMAD_VERSION }}
    - -p:CI=true

  docker:
    docker_file: Dockerfile
    image_name: mfdlabs/grid-bot
    build_args:
      - IMAGE_TAG=${{ env.NOMAD_VERSION }}
    
deployment:
  count: 1

  job: other-redis-test-${{ env.NOMAD_SHORT_ENVIRONMENT }}

  # Passed to the meta section in Nomad
  meta:
    ENVIRONMENT: ${{ env.NOMAD_ENVIRONMENT }}

  containers: # Maps to the groups section in Nomad
    - image: redis
      resources:
        cpu: ${{ env.NOMAD_CPU }}
        ram: ${{ env.NOMAD_RAM }}
      network:
        ports:
          db:
            to: 6379
      services:
        - name: other-redis-test-${{ env.NOMAD_SHORT_ENVIRONMENT }}
          port: db
          tags:
            - ${{ env.NOMAD_ENVIRONMENT }}
 
