name: Deploy

on:
  workflow_dispatch:
    inputs:
      components:
        description: "The list of components to deploy"
        required: true
        type: string
     
jobs:
  parse-input-components:
    name: Validate and find component directories
    runs-on: ubuntu-latest

    outputs:
      components: ${{ steps.find-component-directories.outputs.components }}

    steps:
      # Validate the components input
      # Should be a comma-separated list of components 
      # e.g. "component1,component2,component3" only [a-zA-Z0-9_\-] are allowed for
      # component names
      # at least one component should be provided
      # components can also contain a single colon like:
      # "component1:component1-version,component2:component2-version", and if it does
      # not contain a colon, the version will be set to the latest
      - name: Validate and Find components
        uses: mfdlabs/component-finder-action@v1
        id: find-component-directories
        with:
          components: ${{ github.event.inputs.components }}

  parse-nomad-jobs:
    name: Parse and Validate Components
    runs-on: ubuntu-latest

    needs: parse-input-components

    if: ${{ needs.parse-input-components.outputs.components != '' }}

    outputs:
      nomad-files: ${{ steps.validate-components.outputs.nomad-files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Components
        uses: mfdlabs/component-nomad-parser-action@v4
        id: validate-components # Output here is post validation, any components that do not have a deploy section will be removed
        env:
          NOMAD_ENVIRONMENT: development
          NOMAD_SHORT_ENVIRONMENT: dev
        with:
          components: ${{ needs.parse-input-components.outputs.components }}
