name: Deploy

on:
  workflow_dispatch:
    inputs:
      components:
        description: "The list of components to deploy"
        required: true
        type: string
     
jobs:
  parse-components:
    name: Validate and find component directories
    runs-on: ubuntu-latest

    outputs:
      components: ${{ steps.find-component-directories.outputs.components }}

    env:
      # A list of directories to search for components
      COMPONENTS_SEARCH_DIRS: "api-sites,services,web"
      COMPONENT_CONFIGURATION_FILE_NAME: ".component.yml"

    steps:
      # Validate the components input
      # Should be a comma-separated list of components 
      # e.g. "component1,component2,component3" only [a-zA-Z0-9_\-] are allowed for
      # component names
      # at least one component should be provided
      # components can also contain a single colon like:
      # "component1:component1-version,component2:component2-version", and if it does
      # not contain a colon, the version will be set to the latest
      - name: Validate components input
        id: validate-components
        run: |
          components="${{ github.event.inputs.components }}"
          if [[ ! $components =~ ^([a-zA-Z0-9_\-]+(:[a-zA-Z0-9_\-]+)?)(,([a-zA-Z0-9_\-]+(:[a-zA-Z0-9_\-]+)?))*$ ]]; then
            echo "::error title=Invalid input::Invalid components input, should be a comma-separated list of components"
            exit 1
          fi

          # Transform any component without a version to the latest
          components=$(echo $components | sed 's/[^,]*[^:,]*/&:latest/g') 

          echo "components=$components" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install needed dependencies
        run: npm install js-yaml


      # Find the component directories, look through the COMPONENTS_SEARCH_DIRS for a file named
      # .component-configuration.yml, this file should contain the component name in the yaml field
      # `name: <component-name>`
      - name: Find component directories
        uses: actions/github-script@v7
        id: find-component-directories
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const yaml = require('js-yaml');

            const neededComponents = "${{ steps.validate-components.outputs.components }}".split(",");
            const searchDirs = "${{ env.COMPONENTS_SEARCH_DIRS }}".split(",");

            const foundComponents = [];

            const components = {};

            // Recursively search for the component configuration file
            const searchForComponent = (dir) => {
              if (!fs.existsSync(dir)) {
                core.warning(`Directory ${dir} does not exist`);
                return;
              }

              const files = fs.readdirSync(dir);

              for (const file of files) {
                const filePath = path.join(dir, file);
                const stat = fs.statSync(filePath);

                if (stat.isDirectory()) {
                  searchForComponent(filePath);
                } else if (file === "${{ env.COMPONENT_CONFIGURATION_FILE_NAME }}") {
                  const componentConfig = fs.readFileSync(filePath, 'utf8');
                  const component = yaml.load(componentConfig).name;

                  for (const neededComponent of neededComponents) {
                    if (neededComponent.split(":")[0] === component) {
                      components[neededComponent] = path.resolve(filePath);
                      foundComponents.push(component);
                    }
                  }
                }
              }
            }

            for (const searchDir of searchDirs) {
              searchForComponent(searchDir, neededComponents);
            }

            // Make a warning for each component that was not found
            for (const component of neededComponents) {
              if (!foundComponents.includes(component)) {
                core.warning(`Component ${component} not found`);
              }
            }

            core.setOutput('components', components);

  test-job:
    name: Test job
    runs-on: ubuntu-latest

    needs: parse-components

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        uses: actions/github-script@v7
        with:
          script: |
            const components = ${{ needs.parse-components.outputs.components }};
            console.log(components);
            // Run tests for each component
            for (const component in components) {
              console.log(`Running tests for ${component}`);
            }