name: Deploy

on:
  workflow_dispatch:
    inputs:
      components:
        description: "The list of components to deploy"
        required: true
        type: string
     
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # A list of directories to search for components
      COMPONENTS_SEARCH_DIRS: "api-sites,services,web"
      COMPONENT_CONFIGURATION_FILE_NAME: ".component.yml"

    steps:
      # Validate the components input
      # Should be a comma-separated list of components 
      # e.g. "component1,component2,component3" only [a-zA-Z0-9_\-] are allowed for
      # component names
      # at least one component should be provided
      - name: Validate components input
        run: |
          components="${{ github.event.inputs.components }}"
          if [[ ! $components =~ ^([a-zA-Z0-9_\-]+,)*[a-zA-Z0-9_\-]+$ ]]; then
            echo "::error title=Invalid input::Invalid components input, should be a comma-separated list of components"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install needed dependencies
        run: npm install js-yaml


      # Find the component directories, look through the COMPONENTS_SEARCH_DIRS for a file named
      # .component-configuration.yml, this file should contain the component name in the yaml field
      # `name: <component-name>`
      - name: Find component directories
        uses: actions/github-script@v7
        id: find-component-directories
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const neededComponents = "${{ github.event.inputs.components }}".split(",");
            const searchDirs = "${{ env.COMPONENTS_SEARCH_DIRS }}".split(",");

            const foundComponents = [];

            const components = [];

            // Recursively search for the component configuration file
            const searchForComponent = (dir) => {
              if (!fs.existsSync(dir)) {
                return;
              }

              const files = fs.readdirSync(dir);

              for (const file of files) {
                const filePath = path.join(dir, file);
                const stat = fs.statSync(filePath);

                if (stat.isDirectory()) {
                  searchForComponent(filePath);
                } else if (file === "${{ env.COMPONENT_CONFIGURATION_FILE_NAME }}") {
                  const componentConfig = fs.readFileSync(filePath, 'utf8');
                  const componentConfigYaml = require('js-yaml').load(componentConfig);

                  if (componentConfigYaml.name) {
                    components.push(filePath);
                    foundComponents.push(componentConfigYaml.name);
                  }
                }
              }
            };

            for (const searchDir of searchDirs) {
              searchForComponent(searchDir);
            }

            // Make a warning for each component that was not found
            for (const component of neededComponents) {
              if (!foundComponents.includes(component)) {
                core.warning(`Component ${component} not found`);
              }
            }

            core.setOutput('components', components);

      # Echo the found components
      - name: Echo found components
        run: |
          echo "Found components: ${{ steps.find-component-directories.outputs.components }}"
