name: Test Remote Workflow Dispatch

on:
  workflow_dispatch:
    

jobs:
  test-remote-workflow-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Test Remote Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml
          inputs: '{ "components": "grid-bot:latest" }'
          token: ${{ secrets.ACCESS_TOKEN }}